### ISSUE TITLE
Attachments in transactions

### ISSUE THREAD

**Issue by emansih** [firefly-iii/api-docs-generator#1]
Well, I'm the first to create an issue. 

Reading the doc, I am able to retrieve an attachment from a transaction. But how do I link the attachment to the transaction?

**Comment by JC5** [comment]
Congrats on having issue number one! :tada:

If you want to update an existing attachment, you can use [this endpoint](https://api-docs.firefly-iii.org/#/attachments/updateAttachment). That also allows you to link it to a transaction journal using `journal_id`.

I've made a note to extend this to the transaction id as well.

**Comment by emansih** [comment]
Ok I understand. I will have to have a valid transaction submitted before I can attach an attachment. Can I propose that transactions be submitted together with attachment?

**Comment by JC5** [comment]
Yes, but it's not going to happen. There is a separate endpoint to facilitate binary uploads. Doing this using JSON is a base64 nightmare and would not support multi-part uploads. To upload an attachment you need to:

- [POST a transaction](https://api-docs.firefly-iii.org/#/transactions/storeTransaction)
- [POST an attachment](https://api-docs.firefly-iii.org/#/attachments/storeAttachment)
- [POST the upload](https://api-docs.firefly-iii.org/#/attachments/uploadAttachment)
