### ISSUE TITLE
`TransactionSplit` schema: `source_id` & `destination_id` are marked as required

### ISSUE THREAD

**Issue by GeorgeHahn** [firefly-iii/api-docs-generator#28]
The server allows `TransactionSplit` to define source/dest accounts by name or ID, but the schema defines the IDs as required. It would be preferable to leave both as optional, which would allow generated clients to create transactions using account names.

**Comment by JC5** [comment]
Yes, I'll put them both on nullable instead. There is no "either of these two fields" option in Swagger, right?

**Comment by JC5** [comment]
Oh the push closed the issue. Feel free to re-open if necessary.

**Comment by GeorgeHahn** [comment]
Thanks! It looks like there is not a good solution: [long-standing openapi spec issue](https://github.com/OAI/OpenAPI-Specification/issues/256).
