### ISSUE TITLE
Storing New Attachment

### ISSUE THREAD

**Issue by emansih** [firefly-iii/api-docs-generator#8]
Hi James, I was looking at the docs on storing new attachment(`/api/v1/attachments`) and I have 2 questions. 

1. What is `model` in this context?
2. What is the `model_id`?

Thanks.

**Comment by JC5** [comment]
The model is the object class to which the attachment must be linked. Possible values are Bill, Transaction, TransactionJournal, ImportJob. The model_id is the related ID.

**Comment by emansih** [comment]
Sorry I still do not understand. What is the _related ID_ in the context of attaching an attachment to a transaction?

**Comment by JC5** [comment]
If you submit `model=Transaction`, you must include a valid `model_id=x`, where x is a valid transaction ID. Same for TransactionJournal, where you must provide a valid transaction journal ID.

Same for bills and import jobs.

**Comment by emansih** [comment]
I think(?) there is a bug in the API. Here is what I did.

```
curl -X POST "https://demo.firefly-iii.org/api/v1/attachments" -H "accept: application/json" -H "Authorization: Bearer xxxx" -H "Content-Type: application/json" -d "{\"filename\":\"file.pdf\",\"model\":\"Transaction\",\"model_id\":536,\"title\":\"Some PDF file\",\"notes\":\"Some notes\"}"
```

After that I use the response 

```
curl -X POST \
  https://demo.firefly-iii.org/api/v1/attachments/4/upload \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/x-www-form-urlencoded'
```
![screenshot 36](https://user-images.githubusercontent.com/5896415/53572134-7f20a800-3ba5-11e9-8d04-172b75c8c185.png)
![screenshot 37](https://user-images.githubusercontent.com/5896415/53572139-80ea6b80-3ba5-11e9-9c93-f7a630f97864.png)

No attachment shows up in the transaction details page(https://demo.firefly-iii.org/transactions/show/536)

**Comment by JC5** [comment]
The ID in the URL of the website refers to the `journal_id`. So make sure you browse to correct journal.

**Comment by emansih** [comment]
When I try to upload `text/plain`, everything works as expected. When I try to upload an image(image/jpeg), this appears in the log ` local.ERROR: Mime type application/octet-stream is not allowed for API file upload.`

**Comment by emansih** [comment]
I can't find the allowed mime allowed. Is it controlled by Apache or Firefly III? 
https://github.com/firefly-iii/firefly-iii/blob/143fe2a71f8d8f2873bd0f79ca421e00f91dd5c3/app/Helpers/Attachments/AttachmentHelper.php#L63

**Comment by JC5** [comment]
Firefly III: https://github.com/firefly-iii/firefly-iii/blob/master/config/firefly.php#L117

**Comment by JC5** [comment]
OK, I did some testing using Postman. This resulted in a new attachment object for a Bill. It works the same for an ImportJob, although those are not really useful yet:

```
curl -X POST \
  'https://firefly.local/api/v1/attachments?filename=test.pdf&model=Bill&model_id=7&title=Some%20PDF&notes=Some%20notes' \
  -H 'Accept: application/json' \
  -H 'cache-control: no-cache'
```

I then submit the file using this (Postman screenshot):

![screenshot 2019-03-02 at 08 58 32](https://user-images.githubusercontent.com/5889984/53679168-68737180-3cc9-11e9-8f0f-ea8f8ad9169e.png)

So far so good. For transactions and transaction journals it gets more tricky. Some background: transaction journals always have 2 transactions. One going in, one going out. This is double bookkeeping. When I added split transactions I was an idiot: I added multiple transactions (4, 6 or 8) to the transaction journal. Not very smart (in hindsight) and something I must fix. But OK.

The user interface of Firefly III uses the transaction journal ID in the URL (`/show/transactions/<journalID>`. The API uses transaction ID's. `/api/v1/transactions/<TransactionID>`. You may have noticed that some transaction ID's do not result in the same `{id: xx}`.

So to upload transactions you can use either the transaction ID (which the API uses) or transaction journal ID's (which the frontend uses). Either way, in the database, the file ends up at the **transaction journal**.

So when you post a new attachment to a transaction, this is the (slightly confusing) result:

![screenshot 2019-03-02 at 09 03 15](https://user-images.githubusercontent.com/5889984/53679189-11ba6780-3cca-11e9-9a4b-65ea940a7cfa.png)

I was able to upload JPG files however.

**Comment by emansih** [comment]
the issue was with my code. Thanks for your help. I was using multi-part(RFC 2387) for uploading but digging around it appears that Firefly III does not support it.

**Comment by JC5** [comment]
It’s on the list!
